sudo: required

git:
  quiet: true

env:
  global:
    - ROS_REPO=ros
    - CMAKE_ARGS="-DENABLE_TESTS=ON"
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=dependencies.rosinstall

jobs:
  include:
    - os: linux
      dist: trusty
      language: cpp
      env:
      - ROS_DISTRO="kinetic"
      - CCACHE_DIR=$HOME/.ccache
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: xenial
      language: cpp
      env:
      - ROS_DISTRO="melodic"
      - CCACHE_DIR=$HOME/.ccache
      cache:
        directories:
          - $HOME/.ccache
    - os: windows
      language: cpp

install:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then git clone --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config; fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        unset CXX CXX_FOR_BUILD CC CC_FOR_BUILD
        choco feature disable -n=showDownloadProgress
        cd ..
        mkdir -p catkin_ws/src
        mv descartes_light catkin_ws/src/
        cd catkin_ws
        choco uninstall mingw
#        wget https://raw.githubusercontent.com/johnwason/source_bat/master/source_bat.bash
#        source source_bat.bash 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat'

        pip install -U rosdep rosinstall_generator wstool rosinstall
        curl --output requirements.txt -L https://raw.githubusercontent.com/ms-iot/rosdistro-db/init_windows/rosdistro_cache/catkin-requirements.txt
        pip install -U --no-deps --force-reinstall -r requirements.txt
        python -m pip install -U pip setuptools

        rosdep init
        curl --output 10-ms-iot.list -L https://raw.githubusercontent.com/ms-iot/rosdistro-db/init_windows/rosdep/sources.list.d/10-ms-iot.list
        copy 10-ms-iot.list c:\etc\ros\rosdep\sources.list.d
        rosdep update

        choco source add -n=ros-win -s="https://roswin.azurewebsites.net/api/v2" --priority=1
        choco source disable -n=chocolatey

        set ROSDISTRO_INDEX_URL=https://raw.githubusercontent.com/ms-iot/rosdistro-db/init_windows/index.yaml
        choco install ros-melodic-ros_base -y --execution-timeout=0

        rosdep install --from-paths src --ignore-src -r -y
        /c/opt/vcpkg/vcpkg.exe install jsoncpp:x64-windows
    fi
script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then .ci_config/travis.sh; fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        catkin_make_isolated --cmake-args -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=ON
    fi
